# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logreg_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='birthday',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='quotes',
            field=models.ManyToManyField(related_name='_users_quotes_+', to='logreg_app.Users'),
        ),
    ]
