# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 00:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logreg_app', '0003_users_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='users',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='users',
            name='quotes',
        ),
        migrations.AddField(
            model_name='quote',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_quotes', to='logreg_app.Users'),
        ),
        migrations.AddField(
            model_name='users',
            name='favorites',
            field=models.ManyToManyField(default=None, related_name='favorites', to='logreg_app.Quote'),
        ),
    ]
