# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logreg_app', '0004_auto_20171024_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='content',
            field=models.TextField(),
        ),
    ]
