# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='notes',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
    ]
