# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors', '0002_authors_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='notes',
            field=models.TextField(max_length=1000),
        ),
    ]
