# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors', '0003_auto_20171017_0022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books_authors',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='books_authors',
            name='books',
        ),
        migrations.AddField(
            model_name='authors',
            name='books',
            field=models.ManyToManyField(related_name='authors', to='book_authors.books'),
        ),
        migrations.DeleteModel(
            name='books_authors',
        ),
    ]
