# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_likes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='uploaded_by_id',
        ),
        migrations.AddField(
            model_name='books',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_by', to='book_likes.users'),
        ),
        migrations.AddField(
            model_name='books',
            name='user_likes',
            field=models.ManyToManyField(related_name='user_likes', to='book_likes.users'),
        ),
    ]
